version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: masterspringsecuritydockercompose
    container_name: my-postgres-docker-compose
    volumes:
      - postgres-volume:/var/lib/mysql

  my-app:
    build: .
    image: my-app:v1.2
    ports:
      - "8090:8090"
    container_name: my-app-docker-compose
    depends_on:
      - db

  client:
    image: my-client-app:v1
    ports:
      - "8100:8080"
    container_name: my-client-app-container
    depends_on:
      - my-app

volumes:
  postgres-volume: